version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/containers/anndata-to-ui"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/containers/h5ad-to-arrow"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/containers/mudata-to-ui"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/containers/object-by-analyte-to-ui"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/containers/ome-tiff-metadata"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/containers/ome-tiff-offsets"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/containers/ome-tiff-segments"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/containers/scatac-csv-to-arrow"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/containers/seg-mudata-to-zarr"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/containers/sprm-to-anndata"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/containers/sprm-to-json"
    schedule:
      interval: "monthly"
