services:
  - docker
language: python
python:
  - '3.7'
before-install:
    - sudo apt-get install -y gcc python3-dev
install:
    - pip install -r ./containers/ome-tiff-offsets/context/requirements.txt
script:
  - ./test.sh
