name: CI and Release Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SOURCE_DATE_EPOCH: 1746403200
      REPRO_ZIPFILE_FILE_MODE: '644'
      REPRO_ZIPFILE_DIR_MODE: '755'

    services:
      docker:
        image: docker:20.10.24

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Adjust if needed

      - name: Run Tests
        run: |
          export TERM=xterm
          ./test.sh

  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/')
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create GitHub Release
        run: |
          ./create_release.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}